--CREATE DATABASE PIZZARIA_EXTRA;

USE PIZZARIA_EXTRA;

CREATE TABLE CATEGORIAS(
	ID_CATEGORIA INT IDENTITY PRIMARY KEY
	,NOME_CATEGORIA VARCHAR(50) UNIQUE
);

CREATE TABLE TIPOS_USUARIO(
	ID_TIPO_USUARIO INT IDENTITY PRIMARY KEY
	,NOME_TIPO_USUARIO VARCHAR(50) UNIQUE
);

CREATE TABLE USUARIOS(
	ID_USUARIO INT IDENTITY PRIMARY KEY
	,NOME_USUARIO VARCHAR(200) UNIQUE
	,SENHA CHAR(50)
	,TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPOS_USUARIO(ID_TIPO_USUARIO) 
);

CREATE TABLE PIZZARIAS(
	ID_PIZZARIA INT IDENTITY PRIMARY KEY
	,NOME_PIZZARIA VARCHAR(100)
	,ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS(ID_CATEGORIA)
	,TELEFONE CHAR(12) UNIQUE
	,OPCAO_VEGANA BIT DEFAULT(0)
);