USE PIZZARIA_EXTRA;

INSERT INTO CATEGORIAS(NOME_CATEGORIA) VALUES('$'), ('$$'), ('$$$')

INSERT INTO TIPOS_USUARIO(NOME_TIPO_USUARIO) VALUES('Administrador'), ('Cliente')

INSERT INTO USUARIOS(NOME_USUARIO, SENHA, TIPO_USUARIO) VALUES('Gandolf', '132', 1)

INSERT INTO USUARIOS(NOME_USUARIO, SENHA, TIPO_USUARIO) VALUES('Thomas Tigando', '132', 2)

INSERT INTO PIZZARIAS(NOME_PIZZARIA, ID_CATEGORIA, TELEFONE, OPCAO_VEGANA) VALUES('Pizzaria Tsukamolho', 2, '11940028922', 1)