--CREATE DATABASE PIZZARIA_EXTRA;

USE PIZZARIA_EXTRA;

ALTER TABLE CATEGORIAS(
	ID_CATEGORIA INT IDENTITY PRIMARY KEY
	,NOME_CATEGORIA VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE TIPOS_USUARIO(
	ID_TIPO_USUARIO INT IDENTITY PRIMARY KEY
	,NOME_TIPO_USUARIO VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE USUARIOS(
	ID_USUARIO INT IDENTITY PRIMARY KEY
	,NOME_USUARIO VARCHAR(200) UNIQUE NOT NULL
	,SENHA CHAR(50) NOT NULL
	,TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPOS_USUARIO(ID_TIPO_USUARIO) NOT NULL 
);

CREATE TABLE PIZZARIAS(
	ID_PIZZARIA INT IDENTITY PRIMARY KEY
	,NOME_PIZZARIA VARCHAR(100) NOT NULL
	,ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS(ID_CATEGORIA) NOT NULL
	,TELEFONE CHAR(12) UNIQUE NULL
	,OPCAO_VEGANA BIT DEFAULT(0)
);