USE PIZZARIA_EXTRA;

INSERT INTO CATEGORIAS(NOME_CATEGORIA) VALUES('$'), ('$$'), ('$$$')

INSERT INTO TIPOS_USUARIO(NOME_TIPO_USUARIO) VALUES('Administrador')

INSERT INTO USUARIOS(NOME_USUARIO, SENHA, TIPO_USUARIO) VALUES('Gandolf', '132', 1)